### ISSUE TITLE
URIs should be IRIs

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-ont#32]
Backend counterpart of https://github.com/mmisw/orr-portal/issues/48

(Summary of changes in RDF 1.1, which uses IRIs - https://www.w3.org/TR/rdf11-new/#identifiers)

**Comment by carueda** [comment]
The RFC: https://www.ietf.org/rfc/rfc3987.txt

**Comment by carueda** [comment]
@graybeal  Any comments to my proposal here?

**Comment by graybeal** [comment]
Well, I've perhaps prematurely taken you up on renaming the documentation, most of it now uses the term IRIs. 

I was under the impression that making it possible to use IRIs in software would be basically a matter of using IRI-compatible libraries, and that most libraries at this stage (that we'd be likely to use, anyway) would be IRI-compatible. As I understood it last time I looked (several years ago), IRIs are basically just a different definition of the legal strings allowed, in order to support internationalization. 

So I'm a little surprised if there is a big cost here. Will check a little with the team here.

**Comment by carueda** [comment]
Agree, hopefully no "big cost", but I'd like to get some input that you can get from your team in terms of any gotchas and such.  Yes, the libraries used by ORR have long supported IRIs, but I guess my concern is more at the level of how such IRIs are handled by browsers and client application in terms of corresponding encoding toward transfer to the backend, and how they should be decoded in the backend;  how to properly handle special IRI symbols for display purposes; etc.

**Comment by carueda** [comment]
(just some personal note)

ORR uses both Apache Jena and OWL-API libraries.

Jena: Although claimed to be "incomplete", https://jena.apache.org/documentation/notes/iri.html offers some acceptable description of how to deal with IRIs. In particular, Jena seems to put great attention to **validation**. 

OWL-API:  There's some Javadoc for their [`IRI` class](http://owlcs.github.io/owlapi/apidocs_5/index.html) but no other specific IRI documentation AFAICT (https://github.com/owlcs/owlapi/wiki).  In particular, I'm not seeing any explicit methods to **validate** a string as representing an IRI.
