### ISSUE TITLE
How much of "MMI's Constructing URIs for Ontologies" documentation does orr-ont enforce?

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-ont#48]
Hi @carueda, @graybeal recently pointed me to [MMI's Constructing URIs for Ontologies documentation](http://marinemetadata.org/apguides/ontprovidersguide/ontguideconstructinguris), which makes a very clear case for solid URI construction. I wonder how much of this guidance (best practice???) does orr-ont enforce at the ESIP COR?

**Comment by carueda** [comment]
Hi @lewismc 

Thanks for your question. I'll have to review the document again to give a more concrete answer (also in consideration to the various relevant changes in v3 wrt to the initial ORR version from those times), but for the moment here's some initial response.

>  I wonder how much of this guidance (best practice???)

@graybeal can provide a much better response about the history and status of that document.

> does orr-ont enforce at the ESIP COR?

Not much in general. Again I'll have to review it more detail, but, for example, regarding:

>A) Include the file extension, ...
> 
> 1) http://mmisw.org/ont/mmi/20080701T022342/platform.owl <-- PREFERRED
> 2) http://mmisw.org/ont/mmi/20080701T022342/platform

there is no any such "practice" enforced by the ORR.

**Comment by graybeal** [comment]
Many of these were recommendations on how to publish ontologies generally, applicable to both ontology creators and repositories. As recommendations, we sometimes elected not to fully follow them, and now there are several I would probably choose to update. 

I know we dropped '$' as a placeholder for 'latest version'. I believe we intend to still be supporting the timestamp-version dereferencing, at least of ontologies; but in fact that may have been dropped along the way as well. I am in the process of verifying its status with Carlos.  (It is technologically feasible to re-add it if necessary, since we have the old versions, but it may require some negotiation to make the time commitment possible.)

John

**Comment by carueda** [comment]
The ontguideconstructingiris link now redirects to [ontguideconstructingiris](https://marinemetadata.org/apguides/ontprovidersguide/ontguideconstructingiris), where John has been doing some revisions.

Here are some additional comments by looking at (part of) the new/modified contents:

(John, this includes some observations/suggestions for your ongoing revision, hope including them here is ok.)

> **Standalone File on the Web**
> 
> The IRI representing a single ontology file 

(suggest referring to "ontology resource" instead of to "ontology file" in that document in general)

> should follow the following basic scheme (some modifiers are described later):
> 
> _https://{hostdomain}/{ontologiesRoot}/{authority}/{resourceIdentifier}_

Yes, the ORR basically follows this pattern (for ontologies registered under the  _fully-hosted_ mode, which include those created with the vocabulary and mapping tools unless the user opts to select the full desired IRI for the registration).  Some notes:
-  The actual HTTP scheme corresponds to where the ORR instance is being served. For example, this is **https** for the XDOMES and MMI instances, and is **http** for the COR instance.
- _ontologiesRoot_: corresponds to `ont` in all ORR instances we are aware of. It can be changed to whatever other value if desired. (BTW, it's technically possible to even omit this piece altogether.)

-  _authority_: in v3 this fragment corresponds to the "owner" of the ontology. The owner can be an organization (which basically corresponds to _authority_ in v2), or the username of the submitting  user directly.

> 
> Ideally, the service where the ontology file is served can appropriately serve the file also with an extension according to its type (e..g, RDF, SKOS, or OWL), as in
> 
> _https://{hostdomain}/{ontologiesRoot}/{authority}/{resourceIdentifier}.owl_

To resolve a particular representation format, the ORR v3 mainly supports [content negotiation](https://www.w3.org/TR/2008/NOTE-swbp-vocab-pub-20080828/#negotiation), but also an explicit `format` parameter for convenience. File extension is not supported in v3 but could be reincorporated if needed.

> **Web Resource in a Repository**
> 
> In a repository, it is possible to serve the same ontology as multiple resources, using a combination of ...

Just to note that the ontology is "the resource," which can be resolved in a variety of possible [formats/ serializations](https://www.w3.org/2001/sw/SW-FAQ#serialization).

**Comment by carueda** [comment]
@lewismc Lewis, I'm closing this as resolved. Feel free to let me know of any further questions and/or enter new issues as needed.

**Comment by lewismc** [comment]
Nothing for the time being. Thank you for commenting here, it makes excellent reference for the ESIP SemTech Committee to move forward. @graybeal please also consider reviewing the comments from @carueda above. If we decide to move SWEET forward based upon the above referenced document (which I strongly support) then we should make sure the ORR/COR provides complete supporting functionality.
